#define GPIO0_CONF          0x00
#define GPIO1_CONF          0x01
#define GPIO2_CONF          0x02
#define GPIO3_CONF          0x03
#define SYNT3               0x05
#define SYNT2               0x06
#define SYNT1               0x07
#define SYNT0               0x08
#define IF_OFFSET_ANA       0x09
#define IF_OFFSET_DIG       0x0A
#define CHSPACE             0x0C
#define CHNUM               0x0D
#define MOD4                0x0E
#define MOD3                0x0F
#define MOD2                0x10
#define MOD1                0x11
#define MOD0                0x12
#define CHFLT               0x13
#define AFC2                0x14
#define AFC1                0x15
#define AFC0                0x16
#define RSSI_FLT            0x17
#define RSSI_TH             0x18
#define AGCCTRL4            0x1A
#define AGCCTRL3            0x1B
#define AGCCTRL2            0x1C
#define AGCCTRL1            0x1D
#define AGCCTRL0            0x1E
#define ANT_SELECT_CONF     0x1F
#define CLOCKREC2           0x20
#define CLOCKREC1           0x21
#define PCKTCTRL6           0x2B
#define PCKTCTRL5           0x2C
#define PCKTCTRL4           0x2D
#define PCKTCTRL3           0x2E
#define PCKTCTRL2           0x2F
#define PCKTCTRL1           0x30
#define PCKTLEN1            0x31
#define PCKTLEN0            0x32
#define SYNC3               0x33
#define SYNC2               0x34
#define SYNC1               0x35
#define SYNC0               0x36
#define QI                  0x37
#define PCKT_PSTMBL         0x38
#define PROTOCOL2           0x39
#define PROTOCOL1           0x3A
#define PROTOCOL0           0x3B
#define FIFO_CONFIG3        0x3C
#define FIFO_CONFIG2        0x3D
#define FIFO_CONFIG1        0x3E
#define FIFO_CONFIG0        0x3F
#define PCKT_FLT_OPTIONS    0x40
#define PCKT_FLT_GOALS4     0x41
#define PCKT_FLT_GOALS3     0x42
#define PCKT_FLT_GOALS2     0x43
#define PCKT_FLT_GOALS1     0x44
#define PCKT_FLT_GOALS0     0x45
#define TIMERS5             0x46
#define TIMERS4             0x47
#define TIMERS3             0x48
#define TIMERS2             0x49
#define TIMERS1             0x4A
#define TIMERS0             0x4B
#define CSMA_CONF3          0x4C
#define CSMA_CONF2          0x4D
#define CSMA_CONF1          0x4E
#define CSMA_CONF0          0x4F
#define IRQ_MASK3           0x50
#define IRQ_MASK2           0x51
#define IRQ_MASK1           0x52
#define IRQ_MASK0           0x53
#define FAST_RX_TIMER       0x54
#define PA_POWER8           0x5A
#define PA_POWER7           0x5B
#define PA_POWER6           0x5C
#define PA_POWER5           0x5D
#define PA_POWER4           0x5E
#define PA_POWER3           0x5F
#define PA_POWER2           0x60
#define PA_POWER1           0x61
#define PA_POWER0           0x62
#define PA_CONFIG1          0x63
#define PA_CONFIG0          0x64
#define SYNTH_CONFIG2       0x65
#define VCO_CONFIG          0x68
#define VCO_CALIBR_IN2      0x69
#define VCO_CALIBR_IN1      0x6A
#define VCO_CALIBR_IN0      0x6B
#define XO_RCO_CONF1        0x6C
#define XO_RCO_CONF0        0x6D
#define RCO_CALIBR_CONF3    0x6E
#define RCO_CALIBR_CONF2    0x6F
#define PM_CONF4            0x75
#define PM_CONF3            0x76
#define PM_CONF2            0x77
#define PM_CONF1            0x78
#define PM_CONF0            0x79
#define MC_STATE1           0x8D
#define MC_STATE0           0x8E
#define TX_FIFO_STATUS      0x8F
#define RX_FIFO_STATUS      0x90
#define RCO_CALIBR_OUT4     0x94
#define RCO_CALIBR_OUT3     0x95
#define VCO_CALIBR_OUT1     0x99
#define VCO_CALIBR_OUT0     0x9A
#define TX_PCKT_INFO        0x9C
#define RX_PCKT_INFO        0x9D
#define AFC_CORR            0x9E
#define LINK_QUALIF2        0x9F
#define LINK_QUALIF1        0xA0
#define RSSI_LEVEL          0xA2
#define RX_PCKT_LEN1        0xA4
#define RX_PCKT_LEN0        0xA5
#define CRC_FIELD3          0xA6
#define CRC_FIELD2          0xA7
#define CRC_FIELD1          0xA8
#define CRC_FIELD0          0xA9
#define RX_ADDRE_FIELD1     0xAA
#define RX_ADDRE_FIELD0     0xAB
#define RSSI_LEVEL_RUN      0xEF
#define DEVICE_INFO1        0xF0
#define DEVICE_INFO0        0xF1
#define IRQ_STATUS3         0xFA
#define IRQ_STATUS2         0xFB
#define IRQ_STATUS1         0xFC
#define IRQ_STATUS0         0xFD
#define TX_FIFO             0xFF
#define RX_FIFO             0xFF
